# tasks file for haproxy
---
- name: configuration | update file
  template:
    src: "{{ haproxy_conf_template }}"
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0640
    validate: 'haproxy -f %s -c'
  notify: restart haproxy
  tags:
    - haproxy-configuration-update-file

- name: Remove blank lines in order to have a readable config file
  replace:
    path: /etc/haproxy/haproxy.cfg
    after: 'global'
    regexp: '(^\s*$)'
    replace: ''
